[package]
name = "ns-vpn"
version = "0.0.1"
description = "NS VPN - A modern proxy GUI client based on Tauri + Vue"
authors = ["you"]
license = "GPL-3.0-only"
default-run = "ns-vpn"
build = "build.rs"
edition = "2021"
rust-version = "1.77"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [
  "devtools",
  "tray-icon",
  "image-ico",
  "image-png",
] }
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-process = "2"
tauri-plugin-autostart = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml_ng = "0.9"
serde_yaml = "0.9"
tokio = { version = "1", features = ["full"] }
parking_lot = "0.12"
log = "0.4"
opener = "0.7"
reqwest = { version = "0.12", features = ["json"] }
dirs = "6"
base64 = "0.22"
flate2 = "1"
meow-app = { version = "0.19", default-features = false, features = [
  "ss", "trojan", "vless", "vless-vision", "vless-encryption", "vmess",
  "snell", "hysteria2", "ech-tls-tunnel", "dns-server", "dns-encrypted",
  "listener-http", "listener-socks5", "listener-tproxy", "listener-mixed",
] }
meow-config = { version = "0.19", default-features = false, features = [
  "ss", "trojan", "vmess", "vless", "vless-vision", "vless-encryption",
  "snell", "hysteria2", "anytls",
] }
meow-tunnel = "0.19"
meow-dns = { version = "0.19", default-features = false, features = [
  "dns-server", "encrypted",
] }
meow-api = "0.19"
meow-common = "0.19"
meow-listener = { version = "0.19", default-features = false, features = [
  "listener-mixed", "listener-http", "listener-socks5",
] }
sysinfo = "0.38"
dashmap = "6"
uuid = { version = "1", features = ["v4"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "time"] }
tracing-log = "0.2.0"
urlencoding = "2.1.3"
futures-util = "0.3.33"
chrono = "0.4.45"
tracing = "0.1.44"
